apiVersion: v1
kind: Namespace
metadata:
  name: dfgsdfsdf-prod
  labels:
    environment-id: env_2f170739-37d4-4e3a-a530-ba51cc430dc2
    project-id: project_8cc7f458-c70e-4839-834f-60deb683efe3
    project-name: dfgsdfsdf
    environment-name: prod
    organization-id: org_cadb9844-6d6d-4c7a-b6e4-191a4a18ad51
